### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by minsOne** [minsOne/iOSApplicationTemplate#9]
스크립트 작성

- [ ]  Lottie 파일 -> 변수 코드 생성 스크립트 작성
- [ ]  WebP 파일 -> 변수 코드 생성 스크립트 작성
- [ ]  Storyboard 파일 -> 변수 코드 생성 스크립트 작성
- [ ]  Xib 파일 -> 변수 코드 생성 스크립트 작성
